universe       = docker
docker_image   = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable     = /bin/bash
arguments      = /home/atml_team061/tml26_task2/condor/run_shadow_27.sh
initialdir     = /home/atml_team061/tml26_task2
output         = /home/atml_team061/tml26_task2/runlogs/shadow_27.$(ClusterId).$(ProcId).out
error          = /home/atml_team061/tml26_task2/runlogs/shadow_27.$(ClusterId).$(ProcId).err
log            = /home/atml_team061/tml26_task2/runlogs/shadow_27.$(ClusterId).log
should_transfer_files = YES
getenv         = True
request_GPUs   = 1
request_CPUs   = 4
request_memory = 12G
requirements   = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
